# Generated by Django 3.2.9 on 2021-11-17 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='follow',
            options={'ordering': ('-subscription_date',), 'verbose_name': 'подписку', 'verbose_name_plural': 'подписки'},
        ),
    ]
